server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/myproject?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: xhj970829
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 1
      max-wait-millis: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-total: 20
  thymeleaf:
    cache: false
    suffix: .html
    enabled: true
    encoding: utf-8
  resources:
    static-locations: classpath:/static/


logging:
  level:
    com:
      hifix:
        springbootmyfirstproject:
          dao: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml

